# permissions for end users to edit ingresstemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ingresstemplate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ingresstemplate
    app.kubernetes.io/part-of: ingresstemplate
    app.kubernetes.io/managed-by: kustomize
  name: ingresstemplate-editor-role
rules:
- apiGroups:
  - networking.stiil.dk
  resources:
  - ingresstemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.stiil.dk
  resources:
  - ingresstemplates/status
  verbs:
  - get
